<template>
    <div class="backdrop" v-on:click.self="closePreview">
        <div class="modalContainer">

            <button type="button" class="closePreviewBtn" v-on:click="closePreview">X</button>

            <embed class="embedPdf" v-if="srcUrl" :src="srcUrl" type="application/pdf">

            <!-- <iframe class="embedPdf" v-if="srcUrl" :src="srcUrl" frameborder="0"></iframe> -->

            <!-- <table id="pdfTable">
                <h3>{{ song.songName }}</h3>
                <tr>
                    <th>Section Name<br><i>Description</i></th>
                    <th>Time Signature</th>
                    <th>Tempo</th>
                    <th>Bars</th>
                    <th>Start Bar</th>
                    <th>End Bar</th>
                    <th>Gradual Tempo Transition?</th>
                </tr>
                <tr v-for="section in song.sections" v-bind:section="section" v-bind:key="section.id">
                    <td>{{ section.sectionName }}<br><small><i>{{ section.description }}</i></small></td>
                    <td>{{ section.beatsPerBar }} / {{ section.beatValue }}</td>
                    <td>{{ section.tempo }}</td>
                    <td>{{ section.numBars }}</td>
                    <td>{{ section.startBar }}</td>
                    <td>{{ section.endBar }}</td>
                    <td>{{ section.gradualToNext === false ? 'No' : 'Yes' }}</td>  
                </tr>        
            </table> -->

        </div>
    </div>

    
</template>

<script>
import { jsPDF } from "jspdf"
import autoTable from "jspdf-autotable"

export default {
    name: 'PdfPreviewComponent',
    props: ['song'],
    created() {
        // console.log("PdfPreviewModal.vue, created,\n" + JSON.stringify(this.song))
        this.generatePdf()
    },
    // beforeMount() {
    //     console.log("PdfPreviewModal.vue, beforeMount,\n" + JSON.stringify(this.song))
    // },
    data() {
        return {
            // previewShowing: false,
            srcUrl: '',
            // song: this.song, 
        }
    },
    // computed: {
    //     //
    // },
    methods: {
        closePreview() {
            this.$emit('previewCloseClick')
        },
        generatePdf() {
            // console.log(this.song.songName)
            let doc = new jsPDF()

            // autoTable(doc, { html: '#pdfTable'}) // Doesn't work?

            // set some default document properties
            doc.setDocumentProperties({
                title: this.song.songName,
                subject: "A tempo track PDF generated by Tempo Track Creator.",
                // author: "Anonymous",
                keywords: "tempo-track-creator, generated, pdf",
                creator: "Tempo Track Creator"
            });

            // set the header text to the song name
            let headerText = this.song.songName

            // let pageHeight = doc.internal.pageSize.height || doc.internal.pageSize.getHeight();
            let pageWidth = doc.internal.pageSize.width || doc.internal.pageSize.getWidth();

            doc.setTextColor('#000000')
            doc.setFont('helvetica')
            doc.setFontSize(22)

            doc.text(headerText, pageWidth / 2, 15, {
                align: 'center',
            })

            // define the body data
            let sectionRows = []

            for (let i=0; i<this.song.sections.length; i++) {
                let section = this.song.sections[i]
                let nameDesc = section.sectionName + (section.description === '' ? '' : `,\n${section.description}`)
                let row = [
                    nameDesc,
                    `${section.beatsPerBar} / ${section.beatValue}`,
                    section.tempo,
                    section.numBars,
                    section.startBar,
                    section.endBar,
                    (section.gradualToNext === false ? 'No' : 'Yes')
                ]
                sectionRows.push(row)
            }

            // create the table
            autoTable(doc, {
                // theme: 'plain',
                margin: {top: 23, right: 8, left: 8},
                headStyles: {
                    font: 'helvetica',
                    fontStyle: 'normal',
                    fontSize: 13,
                    cellWidth: 'auto',
                    halign: 'left',
                    valign: 'middle',
                    cellPadding: 1,
                    textColor: '#ffffff',
                    fillColor: '#4b4b4b',
                    lineColor: '#6a6a6a',
                    lineWidth: 0.5,
                },
                bodyStyles: {
                    font: 'helvetica',
                    fontStyle: 'normal',
                    fontSize: 11,
                    cellWidth: 'auto',
                    halign: 'left',
                    valign: 'middle',
                    cellPadding: 0.8,
                    textColor: '#000000',
                    fillColor: '#ffffff',
                    lineColor: '#4b4b4b',
                    lineWidth: 0.5
                },
                head: [['Section Name,\nDescription', 'Time\nSignature', 'Tempo', 'Bars', 'Start Bar', 'End Bar', 'Gradual\nTransition\nto Next?']],
                body: sectionRows,
                pageBreak: 'auto', // auto / avoid / always
                rowPageBreak: 'avoid', // auto / avoid
            })

            // output the doc
            // A string identifying one of the possible output types. Possible values are 'arraybuffer', 'blob', 'bloburi'/'bloburl', 'datauristring'/'dataurlstring', 'datauri'/'dataurl', 'dataurlnewwindow', 'pdfobjectnewwindow', 'pdfjsnewwindow'.
            let string = doc.output('bloburi');

            // set the srcUrl used for the embed to this
            // additional # parameters control pdf display options, some dependent on browser
            this.srcUrl = string + "#view=FitV&zoom=60&toolbar=0&navpanes=0&scrollbar=0&statusbar=0&messages=0";
        }
    }
}
</script>

<!-- <style scoped>
#pdfTable {
    background: black;
}
</style> -->